### ISSUE TITLE
Register a new version of the package that uses GSL_jll artifacts

### ISSUE THREAD

**Issue by ViralBShah** [JuliaMath/GSL.jl#106]
#104 updates GSL.jl to use artifacts. Are we ready to tag a new version of this package - 0.7?

**Comment by ViralBShah** [comment]
Mixed up the PRs I was making. I just merged #104 for this.

**Comment by kongdd** [comment]
Thank you! solved

**Comment by giordano** [comment]
Fixed by #108 (and #109)
