### ISSUE TITLE
drone.io pipeline failing

### ISSUE THREAD

**Issue by ludvigak** [JuliaMath/GSL.jl#114]
The drone.io recently started failing for "linux - arm - Julia 1.4".

@giordano any clue why?

**Comment by giordano** [comment]
"v1.4" means "v1.4.2", because that's the latest Julia release in the v1.4 series, but official Julia builds for armv7l are intermittent, and the latest one was v1.4.1

**Comment by ludvigak** [comment]
Wow, fast work!
