### ISSUE TITLE
upgrade to GSL 2.7

### ISSUE THREAD

**Issue by lucifer1004** [JuliaMath/GSL.jl#116]
GSL 2.7 has been [released](http://git.savannah.gnu.org/cgit/gsl.git/tree/NEWS). Is there any time schedule for an update?

**Comment by giordano** [comment]
Isn't this package already using GSL v2.7?
```julia
(jl_YwsJrI) pkg> st -m
      Status `/tmp/jl_YwsJrI/Manifest.toml`
  [92c85e6c] GSL v1.0.1
  [692b3bcd] JLLWrappers v1.3.0
  [21216c6a] Preferences v1.2.2
  [1b77fbbe] GSL_jll v2.7.1+0
```

**Comment by lucifer1004** [comment]
@giordano Oh, yes. The `README.md` should be updated.
