### ISSUE TITLE
Include slightly higher-level interface, for example manage rng allocation

### ISSUE THREAD

**Issue by jlapeyre** [JuliaMath/GSL.jl#118]
EDIT: The example below is broken:
I think the thing returned by `unsafe_load(gslrng)` goes out of scope after the call to `gsl_rng`. So the finalizer is allowed to be called immediately.
In any case, I working version with the intended behavior would be very nice.

Here is an example:
```julia
"""
    gsl_rng(rng_type = GSL.gsl_rng_taus2)

Allocate and return a gsl rng. The storage wil be freed by Julia's garbage collector.
Do not call `GSL.rng_free` on the returned rng. If you do, Julia will exit with a double free error.
"""
function gsl_rng(rng_type = GSL.gsl_rng_taus2)
    gslrng = GSL.rng_alloc(rng_type)
    finalizer(x -> GSL.rng_free(gslrng), unsafe_load(gslrng)) 
    return gslrng
end
```

This is certainly more convenient, and I think it's also less dangerous. As is it, calling `rng_free` twice on an allocated rng will cause Julia to crash. If you use the interface above, the rule is "never call `rng_free`".

There may be other resources that could be managed similarly.

Also, there are several cases where say, both `Vector` and its length are passed, which is redundant.

**Comment by ludvigak** [comment]
Hi John!
Most of GSL.jl is auto-generated from the C headers, so it's really a rather raw interface to the underlying library. Hence the possibility of shooting yourself in the foot by trying to free the same resource twice.

Something on the lines of your suggestion seems like a good idea. Hand-written wrappers are easily added to `src/manual_wrappers.jl`, so if you have the time then you're welcome to write a pull request.

**Comment by jlapeyre** [comment]
Great. I saw `src/manual_wrappers.jl`. That might be a good place. 

Regarding delegating freeing storage to the GC. It turns out it might not a good idea to provide an interface for general use. See [this discussion](https://discourse.julialang.org/t/best-way-to-have-gc-manage-freeing-c-allocated-storage/86233).
