### ISSUE TITLE
Convert `gsl_vector` and `gsl_matrix` outputs to Julia native `Vector` and `Matrix` types

### ISSUE THREAD

**Issue by jiahao** [JuliaMath/GSL.jl#13]
Follow-up to #12

**Comment by harrisonwfw** [comment]
Hi, I would like to ask a (maybe stupid) question, since you removed gsl_matrix_* functions from the library, then how do I call GSL functions that requires input of a gsl_matrix type? Don't I need to convert the Julia Matrix to the GSL type first before I can call the function?

**Comment by ludvigak** [comment]
Actually, `gsl_matrix_*` and `gsl_vector_*` functions are included now (currently on master, but just drafted a new release). The functions `wrap_gsl_matrix` and `wrap_gsl_vector` can be used to wrap them in a Julia array pointing to the data allocated by GSL:

```julia
julia> m = GSL.matrix_alloc(3,3)
Ptr{gsl_matrix} @0x0000000002485f50

julia> GSL.matrix_set_zero(m)

julia> M = GSL.wrap_gsl_matrix(m)
3×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
```

Also:
```julia
help?> GSL.wrap_gsl_matrix
  wrap_gsl_matrix(m::Ptr{gsl_matrix}) -> Array{Float64,2}

  Return a Julia matrix wrapping the data of a gsl_matrix

  REMEMBER that GSL stores matrices in row-major, so matrix will be transposed.
```
