### ISSUE TITLE
Variable not defined when using `integration_qawc` inside a function with local variables.

### ISSUE THREAD

**Issue by Sollovin** [JuliaMath/GSL.jl#138]
Hi, I want to calculate the cauchy principle value integration of a three arguments function inside a function with two arguments decided at runtime with local variables. But it seemed that `integration_qawc` will not find the local variables. Minimal code to repeate the situation is given as follows,
```julia
using GSL

fdist(ε::Float64, μ::Float64, kbt::Float64) = 1.0 / (exp((ε - μ)/kbt) + 1.0)

function genΛ2h(i, j, α, ϵ, t, μ, kbt)
    ws_size = 100
    ws = integration_workspace_alloc(ws_size)

    if α == 1
        f = @gsl_function(x -> (1 - fdist(x, μ[1], kbt)))
    else
        f = @gsl_function(x -> (1 - fdist(x, μ[2], kbt)))
    end

    result = Cdouble[0]
    abserr = Cdouble[0]

    integration_qawc(f, -1000, 1000, ϵ[j], 1e-9, 1e-9, 100, ws, result, abserr)

    return - t[i,α] * t[j,α]' * result[1] / (2*π)
end

genΛ2h(1, 1, 1, [1., 1.], [[1e-2 1e-2];[1e-2 1e-2]], [1.5, -1.5], 0.6)
```
with `ERROR: UndefVarError: μ not defined`.

Any suggestions for making the code to work?

**Comment by yuyichao** [comment]
This is the limitation for the `@gsl_function` macro and cannot be fixed. On the master version you can just omit the `@gsl_function` and it would work.

**Comment by Sollovin** [comment]
Ok, I got. Thanks a lot for your reply.

But I do find a way to avoid the local variables as follows,
```julia
eval(Meta.parse("f = x -> (1 - fdist(x, $(μ[α]), $kbt))"))

#...

integration_qawc(@gsl_function(f), -1000, 1000, ϵ[j], 1e-9, 1e-9, 100, ws, result, abserr)
```

**Comment by yuyichao** [comment]
No please don't do that.
