### ISSUE TITLE
how to get a pointer to gsl_interp_type?

### ISSUE THREAD

**Issue by floswald** [JuliaMath/GSL.jl#19]
Hi!
i was trying to implement this example: http://www.gnu.org/software/gsl/manual/html_node/Interpolation-Example-programs.html#Interpolation-Example-programs

it seems all pretty straightforward except the point where I want to do 

``` julia
pS = spline_alloc(interp_cspline,n)
```

and it tells me that `interp_cspline` is not defined. I tried to do something like `Ptr(gsl_interp_type)` or `Ptr{gsl_interp_type}`. I'm lacking some basic "how to allocate a pointer" knowledge, sorry. 

the rest seems to work just fine, for example that 

``` julia
julia> A = interp_accel_alloc()
Ptr{gsl_interp_accel} @0x0000000101385110
```

i was looking for an equivalent `interp_type_alloc()` but couldnt find any. thanks!

**Comment by ludvigak** [comment]
Interpolation now seems to work, see the basic linear interpolation example in https://github.com/JuliaMath/GSL.jl/blob/master/test/interp.jl
