### ISSUE TITLE
missing integrand in QAWF routine?

### ISSUE THREAD

**Issue by mzaffalon** [JuliaMath/GSL.jl#62]
Is the integrand missing in `integration_qawf` signature?

Other integration routines have the integrand as the first argument:
```
integration_cquad(f::Ref{gsl_function}, ...)
integration_qng(f::Ref{gsl_function},...)
```

[Post on discourse](https://discourse.julialang.org/t/gsls-qawf-integration-for-oscillatory-functions/3040?u=mzaffalon)

**Comment by ludvigak** [comment]
QAWF quadrature seems to working now, see updates example in https://github.com/JuliaMath/GSL.jl/blob/master/examples/Quadrature.jl
