### ISSUE TITLE
Wigner d functions were not wrapped

### ISSUE THREAD

**Issue by mmikhasenko** [JuliaMath/GSL.jl#66]
The function ```gsl_sf_wigner_drot``` is missing in julia wrapper (see ```gnu_gsl/contrib/wigner.h```)
I need it for my calculations. Do you suggest me adding it and requesting a merge?

I found an old comment on the same issue https://savannah.gnu.org/bugs/?46677
Unfortunately, none responded to this guy.

**Comment by ludvigak** [comment]
Since `gsl_sf_wigner_drot` is not part of the standard GSL library, I don't think it makes sense to add it.

**Comment by mmikhasenko** [comment]
UPD: I found the functions in `SymPy` module
```python
from sympy.physics.quantum.spin import Rotation
rot = Rotation.D(1, 1, 0, pi, pi/2, 0)
rot.doit()
```
In principle, one should be able to call them with [`SymPy`](https://github.com/JuliaPy/SymPy.jl).
(I guess the [Physics module](https://github.com/JuliaPy/SymPy.jl/blob/5ef448d1f4f6d04515adb2f3344e37aa270752c7/src/physics.jl) to be extended)
