### ISSUE TITLE
set gsl_rng_type from Julia

### ISSUE THREAD

**Issue by SHIccc** [JuliaMath/GSL.jl#67]
Hi, I try to call the GSL random number generator from Julia. It works well, but I can't change gsl_rng_type and can only take the default algorithm. I found the following code from the package. Could you please give an example about setting "gsl_rng_type"? Many thanks! Danke schön!

best
Chong

function rng_alloc(T::Ref{**gsl_rng_type**})
    output_ptr = ccall( (:gsl_rng_alloc, libgsl), Ptr{gsl_rng},
        (Ref{gsl_rng_type}, ), T )
    output_ptr==C_NULL ? throw(GSL_ERROR(8)) : output_ptr
end

**Comment by ludvigak** [comment]
This now appears to work on the master branch:
```
julia> using GSL

julia> r = rng_alloc(gsl_rng_taus)
Ptr{gsl_rng} @0x0000000002919820

julia> rng_uniform(r)
0.18691460322588682

julia> rng_uniform(r)
0.9510397978592664

julia> rng_free(r)
```
