### ISSUE TITLE
Planning upgrade to GSL 2

### ISSUE THREAD

**Issue by giordano** [JuliaMath/GSL.jl#81]
Currently this package is based on GSL 1.16, which is quite old now.  I've already prepared a build for GSL 2.5: https://github.com/giordano/GSLBuilder.jl/releases/tag/v2.5  As soon as maintainers decide to upgrade, you only need to take https://github.com/giordano/GSLBuilder.jl/releases/download/v2.5/build_GSL.v2.5.0.jl (and probably adapt to support Julia 0.6).

One thing that could be improved is to use OpenBLAS, instead of the internal GSLCBLAS, as suggested by @simonbyrne at https://github.com/JuliaMath/GSL.jl/pull/71#issuecomment-428815187.  I know how to use another build script as a dependency, but I don't know how to convince GSL to build against OpenBLAS.  I couldn't find a configuration option for that, probably I should somehow replace GSLCBLAS with OpenBLAS?

**Comment by simonbyrne** [comment]
So my understanding of how library linking works is pretty poor, so I may be wrong here, but it looks like the `libgsl.so` isn't actually linked against the BLAS. e.g.
```
$ ldd lib/libgsl.so.23.1.0
	linux-vdso.so.1 =>  (0x00007ffd75f81000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb406179000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb405d99000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb406a2b000)
```

Looking [at the docs](https://www.gnu.org/software/gsl/doc/html/usage.html#linking-programs-with-the-library), it seems that they require you to link the resulting _executable_ against CBLAS. So in that case, I don't think you need to actually do anything?

**Comment by giordano** [comment]
Yeah, that makes sense.  So this ticket can be used to track the status of upgrade to GSL 2

**Comment by ludvigak** [comment]
Things are coming along well. Most functions and symbols seem to get wrapped correctly, and I managed to get all examples working:
https://github.com/ludvigak/GSL.jl/tree/gsl2/examples

**Comment by ludvigak** [comment]
#87
